package tracker.enums;

public enum EndPoint {
    GET_TASKS,
    GET_TASKSBYID,
    GET_SUBTASKS,
    GET_SUBTASKBYID,
    GET_EPICS,
    GET_EPICBYID,
    GET_EPICSUBTASKS,
    GET_HISTORY,
    GET_PRIORITIZED,
    POST_TASKS,
    POST_SUBTASKS,
    POST_EPICS,
    DELETE_TASK,
    DELETE_SUBTASK,
    DELETE_EPIC,
    UNKNOWN
}
